@extends('layouts.auth')
@section('title', 'Two-factor challenge')

@php($subtitle = 'Enter the code from your authenticator app')

@section('content')
<form method="POST" action="{{ route('two-factor.store') }}" class="space-y-5">
    @csrf

    <x-input
        name="code"
        label="Authentication code"
        placeholder="123456"
        required
        hint="Enter the 6-digit code generated by your authenticator app."
        autofocus
    />

    <x-btn type="submit" class="w-full justify-center">Verify and continue</x-btn>
</form>

<p class="mt-6 text-center text-sm text-gray-500">
    Wrong account? <a href="{{ route('login') }}" class="text-indigo-600 font-medium hover:text-indigo-700">Sign in again</a>
</p>
@endsection
